AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-055e3d4f0bbeb5878 # ImageID valid only in us-east-1 region
      InstanceType: t2.nano
